<?php
function my_second_module_menu(){
    $items = array(); // инициализируем массив наших пунктов меню
     
    $items['my_form'] = array(  //добавляем страницу по пути 'page_example'
      'title' => 'Пример формы', //заголовок страницы
      'page callback' => 'main_function', //функция возвращающая контент страницы
      'access callback' => TRUE, // разрешаем всем просматривать эту страницу
  );    
    return $items;
}

function main_function(){
    //return t('некая форма');
    $form = drupal_get_form('my_first_form');
    $form = drupal_render($form);
    return $form.'Содержимое тестовой страницы';
    
}

function my_first_form($form, $form_state){
    $form = array();
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('название поля'),
        '#default_value' => t('значение по умолчанию'),
    );
    $form['settings'] = array(
        '#type' => 'radios',
        '#title' => t('Состояние статуса'),
        '#options' => array(
            0 => t('Статус 1'), 
            1 => t('Статус 2')),
        '#description' => t('Описание данного элемента'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );
    return $form;
}

function my_first_form_submit($form, $form_state){
    debug($form_state['values']);
}